### ISSUE TITLE
Symfony 4.0

### ISSUE THREAD

**Issue by hussonkevin** [alchemy-fr/BinaryDriver#22]
Hi,
Could you add support for symfony/process 4.0 ?
Thanks a lot.

**Comment by synt4xy** [comment]
+1.

I'm really looking for support for Symfony 4.0 too. I plan on using the SWFTools on a Laravel 5.6 project, but both of these packages are rendered useless as there's no support for 4.0.

If you could please add this, it would be great. Thank you!

**Comment by jamesgraham** [comment]
It is prepared in #18 we are waiting on a merge 👍

**Comment by jens1o** [comment]
@jamesgraham Is right, but it would be more helpful when I could upload new packages to packagist(composer library), but I'm missing permissions from @romainneutron

**Comment by ChangePlaces** [comment]
any update on this? 4 has been out for quite a while!

**Comment by jens1o** [comment]
This seems unmaintained..

**Comment by liqunx** [comment]
@jens1o clearly

**Comment by tjorim** [comment]
Fixed in #18

**Comment by jens1o** [comment]
thanks :)
