### ISSUE TITLE
packagist pulls version 4.1.0 while master branch seems to be v2.0.0

### ISSUE THREAD

**Issue by tvercruysse** [alchemy-fr/BinaryDriver#25]
## Solution

Update packagist to use v2.0.0

**Comment by jens1o** [comment]
There is no version 4.1?

**Comment by jens1o** [comment]
So shall I dump the version to 5.0? So it continues to work?

**Comment by tvercruysse** [comment]
I was in quite a rush so i commented fast and relentless. i figured since the version located at php-ffmpeg got purged, there would be a stable version at the original repo. i checked packagist and it seemed there was a new version released but it was older than the one packagist uses. so there are still conflicts with symfony ^4.0.0, i wasnt sure it was intended or a small "looked over" mistake.

because now the old vcs solution doesnt work anymore and using composers defaults wont either.

am i correct or am i being a sleep-deprived monkey again ?

**Comment by tvercruysse** [comment]
perhaps change the release tag from v2.0.0 to just 2.0.0 (removing the 'v'). (im not an experienced package maintainer so im only guessing at this point) but packagist used v 1.6.0 while 4.1.0 was there so that should not be the problem. i think you have to tag v2.0.0 as preferred version in packagist or something similar. (again, just shooting what comes to mind here)

**Comment by tjorim** [comment]
@jens1o This is still not resolved, I think a version bump might indeed be the better solution in this case.

**Comment by jens1o** [comment]
@tjorim There's a reason that this issue is not closed. ;)

**Comment by tjorim** [comment]
Great, was just meant as a reminder. I know people's life can be busy but it's been some time and maybe you just forgot. Now there's only one issue: https://github.com/alchemy-fr/Ghostscript-PHP

The alchemy/ghostscript package requires alchemy/binary-driver: ~4.1, so version 5.0 won't be covered. Is this something you are able to fix or do I need to open a new issue? That repo seems a little quiet.

**Comment by jens1o** [comment]
I do not have push access to that repository, so I unfortunately cannot help you. :/

>  That repo seems a little quiet.

So does this. :/ Trying to make it and keep it alive.

**Comment by tvercruysse** [comment]
Would it be possible to revert to version 4.1.x in the meantime? 4.1.1 would be a correct version bump vs 4.1.0 and valid for ghostscript-php. Until ghostscript-php gets updated.

**Comment by tjorim** [comment]
Just update your composer.json in the meantime: for require
alchemy/binary-driver use version "5.0 as 4.2".

In my opinion 4.1.1 is too small seeing the improvements this gives, so
4.2.0 would be better and still valid for alchemy/ghostscript 4.1.
Op zo 30 sep. 2018 19:45 schreef Thomas Vercruysse <notifications@github.com

**Comment by jens1o** [comment]
I did have bad experiences reverting a release. Please do the proposed steps by @tjorim. :)
